services:
  server:
    build:
      context: .
      target: server
    ports:
      - "8080:8080"
    volumes:
      - ./logs:/var/log/lso
    networks:
      - lso-net
    restart: unless-stopped

  client:
    build:
      context: .
      target: client
    profiles:
      - client
    depends_on:
      - server
    stdin_open: true
    tty: true
    networks:
      - lso-net
    command: ["client", "server", "8080"]

networks:
  lso-net:
    driver: bridge
