services:
  server:
    build: .
    container_name: labyrinth_server
    command: ./server_app 5000
    ports:
      - "5000:5000"
    volumes:
      - ./logs:/app/logs

  client:
    build: .
    entrypoint: ["./client_app"]
    depends_on:
      - server
    stdin_open: true
    tty: true
